# -*- coding: utf-8 -*-
"""mp_neuron.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dXgw4Z_Ueo-YTPaYWWjeov4kDG-Baxd
"""

def mp_neuron(input1, input2):
    weight1 = 1
    weight2 = 1
    threshold = 2

    activation = input1 * weight1 + input2 * weight2

    if activation >= threshold:
        return 1
    else:
        return 0

print(mp_neuron(0, 0))
print(mp_neuron(0, 1))
print(mp_neuron(1, 0))
print(mp_neuron(1, 1))